#!/usr/bin/env python3
"""
Nova Sonic AI-to-AI Conversation
Bootstrap with Polly audio, then let Nova Sonic instances converse.

Flow:
1. Customer's opening line generated by Polly -> sent to Agent's Nova Sonic
2. Agent hears it, responds with audio
3. Customer's Nova Sonic hears agent's response, generates reply
4. Back and forth continues
"""

import asyncio
import base64
import json
import os
import wave
import struct
import boto3

# AWS session
session = boto3.Session()
creds = session.get_credentials()
os.environ['AWS_ACCESS_KEY_ID'] = creds.access_key
os.environ['AWS_SECRET_ACCESS_KEY'] = creds.secret_key
if creds.token:
    os.environ['AWS_SESSION_TOKEN'] = creds.token

from aws_sdk_bedrock_runtime.client import BedrockRuntimeClient, InvokeModelWithBidirectionalStreamOperationInput
from aws_sdk_bedrock_runtime.models import InvokeModelWithBidirectionalStreamInputChunk, BidirectionalInputPayloadPart
from aws_sdk_bedrock_runtime.config import Config
from smithy_aws_core.identity.environment import EnvironmentCredentialsResolver

# Audio settings
OUTPUT_RATE = 24000  # Nova produces 24kHz
INPUT_RATE = 16000   # Nova expects 16kHz

# Polly client for bootstrap
polly = boto3.client('polly', region_name='us-east-1')

def generate_polly_audio(text: str, voice_id: str = "Ruth") -> bytes:
    """Generate 16kHz PCM audio using Polly."""
    response = polly.synthesize_speech(
        Text=text,
        OutputFormat='pcm',
        VoiceId=voice_id,
        SampleRate='16000',
        Engine='neural'
    )
    return response['AudioStream'].read()

def resample_24k_to_16k(audio_24k: bytes) -> bytes:
    """Resample 24kHz audio to 16kHz (simple decimation)."""
    samples = []
    for i in range(0, len(audio_24k) - 1, 2):
        samples.append(struct.unpack('<h', audio_24k[i:i+2])[0])
    
    # Take 2 out of every 3 samples (24kHz -> 16kHz)
    resampled = []
    for i in range(0, len(samples), 3):
        resampled.append(samples[i])
        if i + 1 < len(samples):
            resampled.append(samples[i + 1])
    
    return b''.join(struct.pack('<h', s) for s in resampled)


class NovaSonicParticipant:
    """One participant in the conversation."""
    
    def __init__(self, name: str, voice_id: str, system_prompt: str):
        self.name = name
        self.voice_id = voice_id
        self.system_prompt = system_prompt
        self.stream = None
        self.prompt = "p1"
        self.content_num = 1
        self.done = False
        self.audio_out_chunks = []  # Audio we produce
        self.received_response = asyncio.Event()
        self.current_text = ""
        self.all_texts = []
        
    async def send(self, data):
        await self.stream.input_stream.send(
            InvokeModelWithBidirectionalStreamInputChunk(
                value=BidirectionalInputPayloadPart(bytes_=json.dumps(data).encode())
            )
        )
        
    async def connect(self):
        config = Config(
            endpoint_uri="https://bedrock-runtime.us-east-1.amazonaws.com",
            region="us-east-1",
            aws_credentials_identity_resolver=EnvironmentCredentialsResolver(),
        )
        client = BedrockRuntimeClient(config=config)
        self.stream = await client.invoke_model_with_bidirectional_stream(
            InvokeModelWithBidirectionalStreamOperationInput(model_id='amazon.nova-sonic-v1:0')
        )
        print(f"[{self.name}] Connected")
        
    async def setup_session(self):
        """Set up Nova Sonic session."""
        await self.send({"event": {"sessionStart": {"inferenceConfiguration": {"maxTokens": 1024, "temperature": 0.8}}}})
        
        await self.send({"event": {"promptStart": {
            "promptName": self.prompt,
            "textOutputConfiguration": {"mediaType": "text/plain"},
            "audioOutputConfiguration": {
                "mediaType": "audio/lpcm",
                "sampleRateHertz": OUTPUT_RATE,
                "sampleSizeBits": 16,
                "channelCount": 1,
                "voiceId": self.voice_id,
                "encoding": "base64",
                "audioType": "SPEECH"
            }
        }}})
        
        # System prompt
        await self.send({"event": {"contentStart": {
            "promptName": self.prompt,
            "contentName": "sys",
            "type": "TEXT",
            "interactive": False,
            "role": "SYSTEM",
            "textInputConfiguration": {"mediaType": "text/plain"}
        }}})
        await self.send({"event": {"textInput": {
            "promptName": self.prompt,
            "contentName": "sys",
            "content": self.system_prompt
        }}})
        await self.send({"event": {"contentEnd": {"promptName": self.prompt, "contentName": "sys"}}})
        
        print(f"[{self.name}] Session ready (voice: {self.voice_id})")
        
    async def start_audio_turn(self):
        """Start a new audio input turn."""
        content_name = f"audio{self.content_num}"
        await self.send({"event": {"contentStart": {
            "promptName": self.prompt,
            "contentName": content_name,
            "type": "AUDIO",
            "interactive": True,
            "role": "USER",
            "audioInputConfiguration": {
                "mediaType": "audio/lpcm",
                "sampleRateHertz": INPUT_RATE,
                "sampleSizeBits": 16,
                "channelCount": 1,
                "audioType": "SPEECH",
                "encoding": "base64"
            }
        }}})
        
    async def send_audio_chunk(self, audio_16k: bytes):
        """Send a chunk of 16kHz audio."""
        content_name = f"audio{self.content_num}"
        await self.send({"event": {"audioInput": {
            "promptName": self.prompt,
            "contentName": content_name,
            "content": base64.b64encode(audio_16k).decode()
        }}})
        
    async def end_audio_turn(self):
        """End the current audio turn."""
        content_name = f"audio{self.content_num}"
        await self.send({"event": {"contentEnd": {"promptName": self.prompt, "contentName": content_name}}})
        self.content_num += 1
        
    async def receive_responses(self, timeout_seconds: float = 30.0):
        """Receive all responses for the current turn."""
        self.audio_out_chunks = []
        self.current_text = ""
        self.received_response.clear()
        
        start_time = asyncio.get_event_loop().time()
        got_audio = False
        silence_after_audio = 0
        
        while True:
            elapsed = asyncio.get_event_loop().time() - start_time
            if elapsed > timeout_seconds:
                print(f"[{self.name}] Timeout waiting for response")
                break
                
            try:
                output = await asyncio.wait_for(self.stream.await_output(), timeout=0.5)
                result = await output[1].receive()
                
                if result.value and result.value.bytes_:
                    data = json.loads(result.value.bytes_.decode())
                    
                    if 'event' in data:
                        evt = data['event']
                        
                        if 'textOutput' in evt:
                            text = evt['textOutput']['content']
                            role = evt['textOutput'].get('role', '')
                            if role == 'ASSISTANT':
                                self.current_text += text
                                
                        elif 'audioOutput' in evt:
                            audio = base64.b64decode(evt['audioOutput']['content'])
                            self.audio_out_chunks.append(audio)
                            got_audio = True
                            silence_after_audio = 0
                            
                        elif 'contentEnd' in evt:
                            if got_audio:
                                # Response complete
                                break
                                
            except asyncio.TimeoutError:
                if got_audio:
                    silence_after_audio += 0.5
                    if silence_after_audio > 2:
                        # 2 seconds silence after audio = done
                        break
                continue
            except Exception as e:
                if "closed" not in str(e).lower():
                    print(f"[{self.name}] RX Error: {e}")
                break
        
        if self.current_text:
            self.all_texts.append(self.current_text)
            
        return b''.join(self.audio_out_chunks)
        
    async def cleanup(self):
        try:
            await self.send({"event": {"promptEnd": {"promptName": self.prompt}}})
            await self.send({"event": {"sessionEnd": {}}})
        except:
            pass


def save_audio_to_wav(audio: bytes, filename: str, sample_rate: int):
    """Save PCM audio to WAV file."""
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with wave.open(filename, 'wb') as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(sample_rate)
        wf.writeframes(audio)
    print(f"Saved: {filename}")


async def run_conversation():
    # Customer system prompt - natural caller
    customer_prompt = """You are Sarah, a customer calling about a charge on your credit card. You're concerned but not angry.
    
Your situation: You saw a charge for $47.99 from "STREAMTECH SERVICES" that you don't recognize.

Conversation style:
- Speak naturally, like a real person on the phone
- Express some concern about the charge
- Answer questions the agent asks
- If they explain it's a streaming subscription, try to remember if you might have signed up
- Say goodbye politely at the end

Keep responses brief and conversational - 1-3 sentences at a time."""

    # Agent system prompt - helpful support
    agent_prompt = """You are Alex, a friendly customer service agent at ABC Bank.

Your job:
- Greet the customer warmly
- Listen to their concern about the charge
- Help them understand the $47.99 charge from STREAMTECH SERVICES is their streaming subscription (StreamTech Plus)
- Verify it was set up 3 months ago
- Offer to block the merchant if they want to cancel
- Be helpful and empathetic

Keep responses brief - 1-3 sentences. Sound natural, not robotic."""

    print("=" * 60)
    print("🎭 AI-to-AI CONVERSATION WITH POLLY BOOTSTRAP")
    print("=" * 60)
    print("Customer (Sarah/Ruth voice) <---> Agent (Alex/Matthew voice)")
    print("-" * 60)
    
    # Create participants
    customer = NovaSonicParticipant("CUSTOMER", "tiffany", customer_prompt)
    agent = NovaSonicParticipant("AGENT", "matthew", agent_prompt)
    
    # Connect both
    await customer.connect()
    await agent.connect()
    
    await customer.setup_session()
    await agent.setup_session()
    
    all_customer_audio = []
    all_agent_audio = []
    
    try:
        print("\n" + "=" * 60)
        print("CONVERSATION START")
        print("=" * 60)
        
        # TURN 1: Generate customer greeting with Polly -> Agent
        print("\n--- Turn 1: Customer opens ---")
        customer_opening = "Hi, I'm calling about a charge on my account. I saw something for forty-seven ninety-nine from a company called Stream Tech Services, and I don't remember signing up for anything."
        
        # Generate with Polly
        bootstrap_audio = generate_polly_audio(customer_opening, "Ruth")
        all_customer_audio.append(bootstrap_audio)
        print(f"[CUSTOMER]: {customer_opening}")
        
        # Send to Agent's Nova Sonic
        await agent.start_audio_turn()
        
        # Send in chunks to simulate real-time (20ms = 640 bytes at 16kHz)
        chunk_size = 640
        for i in range(0, len(bootstrap_audio), chunk_size):
            chunk = bootstrap_audio[i:i + chunk_size]
            await agent.send_audio_chunk(chunk)
            await asyncio.sleep(0.02)  # 20ms per chunk
        
        # Send silence to trigger VAD
        silence_duration = 2.0  # 2 seconds of silence
        silence_chunk = b'\x00' * 640
        for _ in range(int(silence_duration / 0.02)):
            await agent.send_audio_chunk(silence_chunk)
            await asyncio.sleep(0.02)
        
        await agent.end_audio_turn()
        
        # Get agent's response
        print("\n--- Turn 2: Agent responds ---")
        agent_response_audio = await agent.receive_responses(timeout_seconds=15.0)
        
        if agent_response_audio:
            all_agent_audio.append(agent_response_audio)
            print(f"[AGENT]: {agent.current_text}")
            
            # Now send agent's audio to customer's Nova Sonic
            # Resample 24kHz -> 16kHz
            agent_audio_16k = resample_24k_to_16k(agent_response_audio)
            
            # TURN 3: Customer hears agent, responds
            print("\n--- Turn 3: Customer responds ---")
            await customer.start_audio_turn()
            
            for i in range(0, len(agent_audio_16k), chunk_size):
                chunk = agent_audio_16k[i:i + chunk_size]
                await customer.send_audio_chunk(chunk)
                await asyncio.sleep(0.02)
            
            # Silence for VAD
            for _ in range(int(2.0 / 0.02)):
                await customer.send_audio_chunk(silence_chunk)
                await asyncio.sleep(0.02)
                
            await customer.end_audio_turn()
            
            customer_response_audio = await customer.receive_responses(timeout_seconds=15.0)
            
            if customer_response_audio:
                all_customer_audio.append(customer_response_audio)
                print(f"[CUSTOMER]: {customer.current_text}")
                
                # TURN 4: Agent hears customer, responds
                print("\n--- Turn 4: Agent responds ---")
                customer_audio_16k = resample_24k_to_16k(customer_response_audio)
                
                await agent.start_audio_turn()
                for i in range(0, len(customer_audio_16k), chunk_size):
                    chunk = customer_audio_16k[i:i + chunk_size]
                    await agent.send_audio_chunk(chunk)
                    await asyncio.sleep(0.02)
                    
                for _ in range(int(2.0 / 0.02)):
                    await agent.send_audio_chunk(silence_chunk)
                    await asyncio.sleep(0.02)
                    
                await agent.end_audio_turn()
                
                agent_response_audio_2 = await agent.receive_responses(timeout_seconds=15.0)
                
                if agent_response_audio_2:
                    all_agent_audio.append(agent_response_audio_2)
                    print(f"[AGENT]: {agent.current_text}")
                    
                    # TURN 5: Customer's final response
                    print("\n--- Turn 5: Customer responds ---")
                    agent_audio_16k_2 = resample_24k_to_16k(agent_response_audio_2)
                    
                    await customer.start_audio_turn()
                    for i in range(0, len(agent_audio_16k_2), chunk_size):
                        chunk = agent_audio_16k_2[i:i + chunk_size]
                        await customer.send_audio_chunk(chunk)
                        await asyncio.sleep(0.02)
                        
                    for _ in range(int(2.0 / 0.02)):
                        await customer.send_audio_chunk(silence_chunk)
                        await asyncio.sleep(0.02)
                        
                    await customer.end_audio_turn()
                    
                    customer_response_audio_2 = await customer.receive_responses(timeout_seconds=15.0)
                    
                    if customer_response_audio_2:
                        all_customer_audio.append(customer_response_audio_2)
                        print(f"[CUSTOMER]: {customer.current_text}")
        
        print("\n" + "=" * 60)
        print("CONVERSATION END")
        print("=" * 60)
        
    finally:
        await customer.cleanup()
        await agent.cleanup()
    
    # Save audio files
    print("\n" + "=" * 60)
    print("SAVING AUDIO FILES")
    print("=" * 60)
    
    if all_customer_audio:
        # First is Polly (16kHz), rest is Nova (24kHz) - save separately
        save_audio_to_wav(all_customer_audio[0], "voice_output/ai_convo_customer_polly.wav", INPUT_RATE)
        if len(all_customer_audio) > 1:
            nova_audio = b''.join(all_customer_audio[1:])
            save_audio_to_wav(nova_audio, "voice_output/ai_convo_customer_nova.wav", OUTPUT_RATE)
    
    if all_agent_audio:
        combined_agent = b''.join(all_agent_audio)
        save_audio_to_wav(combined_agent, "voice_output/ai_convo_agent.wav", OUTPUT_RATE)
    
    # Print full transcript
    print("\n" + "=" * 60)
    print("FULL TRANSCRIPT")
    print("=" * 60)
    print(f"\nCustomer said {len(customer.all_texts) + 1} things:")  # +1 for Polly bootstrap
    print(f"  [Polly] {customer_opening}")
    for i, t in enumerate(customer.all_texts, 1):
        print(f"  [{i}] {t}")
        
    print(f"\nAgent said {len(agent.all_texts)} things:")
    for i, t in enumerate(agent.all_texts, 1):
        print(f"  [{i}] {t}")


if __name__ == "__main__":
    asyncio.run(run_conversation())
