#!/usr/bin/env python3
"""
WebRTC Test Setup Helper

Discovers Amazon Connect resources and helps configure the voice tester
for WebRTC testing without phone numbers.

Usage:
    python setup_webrtc.py
"""
import os
import sys
import json
import boto3
from pathlib import Path


def main():
    print("=" * 60)
    print("WebRTC Voice Tester Setup")
    print("=" * 60)
    print()
    
    connect = boto3.client('connect')
    
    # Step 1: List and select Connect instance
    print("Step 1: Finding Amazon Connect instances...")
    try:
        instances_response = connect.list_instances()
        instances = instances_response.get('InstanceSummaryList', [])
    except Exception as e:
        print(f"Error listing instances: {e}")
        return 1
    
    if not instances:
        print("No Amazon Connect instances found!")
        print("Please create an Amazon Connect instance first.")
        return 1
    
    print(f"\nFound {len(instances)} instance(s):\n")
    
    for i, instance in enumerate(instances):
        print(f"  [{i+1}] {instance.get('InstanceAlias', 'No alias')}")
        print(f"      ID: {instance.get('Id')}")
        print(f"      Status: {instance.get('InstanceStatus')}")
        print()
    
    # Select instance
    if len(instances) == 1:
        selected_instance = instances[0]
        print(f"Auto-selecting the only instance: {selected_instance.get('InstanceAlias')}")
    else:
        while True:
            try:
                choice = input("Select instance number: ")
                idx = int(choice) - 1
                if 0 <= idx < len(instances):
                    selected_instance = instances[idx]
                    break
            except (ValueError, IndexError):
                print("Invalid selection. Try again.")
    
    instance_id = selected_instance.get('Id')
    instance_alias = selected_instance.get('InstanceAlias', 'unknown')
    
    print(f"\nSelected: {instance_alias} ({instance_id})")
    
    # Step 2: List contact flows
    print("\n" + "-" * 40)
    print("Step 2: Finding contact flows...")
    
    try:
        flows_response = connect.list_contact_flows(
            InstanceId=instance_id,
            MaxResults=100,
        )
        flows = flows_response.get('ContactFlowSummaryList', [])
    except Exception as e:
        print(f"Error listing contact flows: {e}")
        return 1
    
    if not flows:
        print("No contact flows found!")
        print("Please create a contact flow for testing.")
        return 1
    
    # Filter for relevant flow types
    relevant_types = ['CONTACT_FLOW', 'CUSTOMER_QUEUE', 'CUSTOMER_HOLD']
    relevant_flows = [f for f in flows if f.get('ContactFlowType') in relevant_types]
    
    print(f"\nFound {len(relevant_flows)} relevant contact flow(s):\n")
    
    for i, flow in enumerate(relevant_flows[:20]):  # Show max 20
        print(f"  [{i+1}] {flow.get('Name', 'No name')}")
        print(f"      ID: {flow.get('Id')}")
        print(f"      Type: {flow.get('ContactFlowType')}")
        print()
    
    # Select contact flow
    if len(relevant_flows) == 1:
        selected_flow = relevant_flows[0]
        print(f"Auto-selecting the only flow: {selected_flow.get('Name')}")
    else:
        while True:
            try:
                choice = input("Select contact flow number (or press Enter to skip): ")
                if not choice:
                    selected_flow = None
                    break
                idx = int(choice) - 1
                if 0 <= idx < len(relevant_flows):
                    selected_flow = relevant_flows[idx]
                    break
            except (ValueError, IndexError):
                print("Invalid selection. Try again.")
    
    contact_flow_id = selected_flow.get('Id') if selected_flow else None
    
    # Step 3: Look for Lex bots
    print("\n" + "-" * 40)
    print("Step 3: Finding Lex bots...")
    
    lex = boto3.client('lexv2-models')
    
    try:
        bots_response = lex.list_bots(maxResults=20)
        bots = bots_response.get('botSummaries', [])
    except Exception as e:
        print(f"Note: Could not list Lex bots ({e})")
        bots = []
    
    if bots:
        print(f"\nFound {len(bots)} Lex bot(s):\n")
        for bot in bots:
            print(f"  - {bot.get('botName')}")
            print(f"    ID: {bot.get('botId')}")
            print(f"    Status: {bot.get('botStatus')}")
    else:
        print("No Lex bots found")
    
    # Step 4: Generate configuration
    print("\n" + "-" * 40)
    print("Step 4: Generating configuration...")
    
    env_content = f"""# Voice Tester Configuration
# Generated by setup_webrtc.py

# Amazon Connect
CONNECT_INSTANCE_ID={instance_id}
"""
    
    if contact_flow_id:
        env_content += f"CONTACT_FLOW_ID={contact_flow_id}\n"
    
    env_content += """
# AWS Region 
AWS_REGION=us-east-1

# Testing Mode
# webrtc: Direct Connect connection (no phone number needed)
# pstn: Phone call via Chime SDK (requires phone number)
TEST_MODE=webrtc

# Bedrock Model
BEDROCK_MODEL_ID=anthropic.claude-3-sonnet-20240229-v1:0

# Polly Voice
POLLY_VOICE_ID=Joanna
POLLY_ENGINE=neural
"""
    
    # Write to .env file
    env_path = Path(__file__).parent / '.env'
    
    print(f"\nConfiguration to save:")
    print("-" * 40)
    print(env_content)
    print("-" * 40)
    
    save = input(f"\nSave to {env_path}? [Y/n]: ").strip().lower()
    
    if save != 'n':
        with open(env_path, 'w') as f:
            f.write(env_content)
        print(f"Configuration saved to {env_path}")
    
    # Print next steps
    print("\n" + "=" * 60)
    print("SETUP COMPLETE!")
    print("=" * 60)
    print()
    print("Next steps:")
    print()
    print("1. Deploy the voice tester infrastructure:")
    print("   cd voice_tester && cdk deploy VoiceTestStack")
    print()
    print("2. Run a WebRTC test:")
    print("   python -m voice_tester test scenarios/census_survey_webrtc.yaml")
    print()
    print(f"3. Or run with explicit IDs:")
    print(f"   python -m voice_tester test scenarios/census_survey_webrtc.yaml \\")
    print(f"       --instance-id {instance_id} \\")
    if contact_flow_id:
        print(f"       --contact-flow-id {contact_flow_id}")
    else:
        print(f"       --contact-flow-id <YOUR_FLOW_ID>")
    print()
    
    return 0


if __name__ == '__main__':
    sys.exit(main())
