#!/usr/bin/env python3
"""
Direct Test of Nova Sonic Speech Generation

Tests if Nova Sonic can generate speech output at all.
"""
import asyncio
import base64
import json
import os
import sys
import wave
from pathlib import Path

# Add parent to path
sys.path.insert(0, str(Path(__file__).parent))
from nova_sonic_client import NovaSonicVoiceClient, NovaSonicConfig


async def test_nova_sonic_text_to_speech():
    """Test Nova Sonic's ability to generate speech from text."""
    
    print("="*60)
    print("NOVA SONIC SPEECH TEST")
    print("="*60)
    
    # Initialize Nova Sonic
    config = NovaSonicConfig(region='us-east-1')
    nova = NovaSonicVoiceClient(config)
    nova.set_persona({
        "name": "Test Caller",
        "background": "A friendly caller",
        "attributes": {"speaking_rate": "normal"}
    })
    
    print("Starting Nova Sonic session...")
    await nova.start_session()
    
    # Send a text message to Nova Sonic asking it to respond
    print("Sending text message: 'Hello, please respond with a greeting'")
    await nova.send_text_message("Please say: Hello, I am ready to help you today.")
    
    # Wait for response
    print("Waiting for Nova Sonic to generate speech...")
    await asyncio.sleep(10)
    
    # Collect any audio output
    audio_chunks = []
    while not nova.audio_queue.empty():
        chunk = await nova.get_audio_output()
        if chunk:
            audio_chunks.append(chunk)
            print(f"Received audio chunk: {len(chunk)} bytes")
    
    # End session
    await nova.end_session()
    
    if audio_chunks:
        total_audio = b''.join(audio_chunks)
        print(f"\nTotal audio generated: {len(total_audio)} bytes")
        
        # Save to file
        output_path = '/Users/ChadDHendren/AmazonConnect1/voice_output/nova_speech_test.wav'
        with wave.open(output_path, 'wb') as wav_file:
            wav_file.setnchannels(1)
            wav_file.setsampwidth(2)
            wav_file.setframerate(24000)  # Nova outputs at 24kHz
            wav_file.writeframes(total_audio)
        print(f"Saved to: {output_path}")
        print("Play with: afplay " + output_path)
    else:
        print("\nNo audio generated by Nova Sonic")
        print("Checking if Nova Sonic is properly responding...")


async def test_nova_sonic_raw():
    """Test Nova Sonic with raw Smithy SDK."""
    import boto3
    from aws_sdk_bedrock_runtime.client import (
        BedrockRuntimeClient,
        InvokeModelWithBidirectionalStreamOperationInput
    )
    from aws_sdk_bedrock_runtime.models import (
        InvokeModelWithBidirectionalStreamInputChunk,
        BidirectionalInputPayloadPart
    )
    from aws_sdk_bedrock_runtime.config import Config
    from smithy_aws_core.identity.environment import EnvironmentCredentialsResolver
    
    print("\n" + "="*60)
    print("RAW NOVA SONIC TEST")
    print("="*60)
    
    # Get credentials
    session = boto3.Session()
    credentials = session.get_credentials()
    if credentials:
        frozen = credentials.get_frozen_credentials()
        os.environ['AWS_ACCESS_KEY_ID'] = frozen.access_key
        os.environ['AWS_SECRET_ACCESS_KEY'] = frozen.secret_key
        if frozen.token:
            os.environ['AWS_SESSION_TOKEN'] = frozen.token
    
    # Create client
    config = Config(
        endpoint_uri="https://bedrock-runtime.us-east-1.amazonaws.com",
        region="us-east-1",
        aws_credentials_identity_resolver=EnvironmentCredentialsResolver(),
    )
    client = BedrockRuntimeClient(config=config)
    
    print("Starting stream...")
    stream = await client.invoke_model_with_bidirectional_stream(
        InvokeModelWithBidirectionalStreamOperationInput(model_id="amazon.nova-sonic-v1:0")
    )
    
    async def send_event(event_json: str):
        event = InvokeModelWithBidirectionalStreamInputChunk(
            value=BidirectionalInputPayloadPart(bytes_=event_json.encode('utf-8'))
        )
        await stream.input_stream.send(event)
    
    # Send session start
    print("Sending session start...")
    await send_event(json.dumps({
        "event": {
            "sessionStart": {
                "inferenceConfiguration": {
                    "maxTokens": 500,
                    "topP": 0.9,
                    "temperature": 0.7
                }
            }
        }
    }))
    
    # Send prompt start with audio output
    prompt_name = "test-prompt"
    print("Sending prompt start...")
    await send_event(json.dumps({
        "event": {
            "promptStart": {
                "promptName": prompt_name,
                "textOutputConfiguration": {"mediaType": "text/plain"},
                "audioOutputConfiguration": {
                    "mediaType": "audio/lpcm",
                    "sampleRateHertz": 24000,
                    "sampleSizeBits": 16,
                    "channelCount": 1,
                    "voiceId": "matthew",
                    "encoding": "base64",
                    "audioType": "SPEECH"
                }
            }
        }
    }))
    
    # Send a system message first (REQUIRED)
    sys_content = "sys-content"
    print("Sending SYSTEM content...")
    
    await send_event(json.dumps({
        "event": {
            "contentStart": {
                "promptName": prompt_name,
                "contentName": sys_content,
                "type": "TEXT",
                "interactive": False,
                "role": "SYSTEM",
                "textInputConfiguration": {"mediaType": "text/plain"}
            }
        }
    }))
    
    await send_event(json.dumps({
        "event": {
            "textInput": {
                "promptName": prompt_name,
                "contentName": sys_content,
                "content": "You are a helpful voice assistant. Respond naturally and briefly."
            }
        }
    }))
    
    await send_event(json.dumps({
        "event": {
            "contentEnd": {
                "promptName": prompt_name,
                "contentName": sys_content
            }
        }
    }))
    
    # Now send a USER text message
    content_name = "test-content"
    print("Sending USER text content...")
    
    await send_event(json.dumps({
        "event": {
            "contentStart": {
                "promptName": prompt_name,
                "contentName": content_name,
                "type": "TEXT",
                "interactive": True,
                "role": "USER",
                "textInputConfiguration": {"mediaType": "text/plain"}
            }
        }
    }))
    
    await send_event(json.dumps({
        "event": {
            "textInput": {
                "promptName": prompt_name,
                "contentName": content_name,
                "content": "Hello! Say: I am Nova Sonic and I am ready to help."
            }
        }
    }))
    
    await send_event(json.dumps({
        "event": {
            "contentEnd": {
                "promptName": prompt_name,
                "contentName": content_name
            }
        }
    }))
    
    # Collect responses
    print("Waiting for responses...")
    audio_chunks = []
    text_output = []
    
    try:
        for i in range(50):  # Wait up to 50 iterations
            try:
                output = await asyncio.wait_for(stream.await_output(), timeout=0.5)
                result = await output[1].receive()
                
                if result.value and result.value.bytes_:
                    data = json.loads(result.value.bytes_.decode('utf-8'))
                    
                    if 'event' in data:
                        event = data['event']
                        
                        if 'textOutput' in event:
                            text = event['textOutput']['content']
                            text_output.append(text)
                            print(f"Text: {text[:50]}...")
                            
                        if 'audioOutput' in event:
                            audio = base64.b64decode(event['audioOutput']['content'])
                            audio_chunks.append(audio)
                            print(f"Audio chunk: {len(audio)} bytes")
                            
                        if 'contentEnd' in event:
                            print("Content ended")
                            
            except asyncio.TimeoutError:
                if audio_chunks:
                    break  # Got enough
                continue
                
    except Exception as e:
        print(f"Error: {e}")
    
    # Close stream
    await send_event(json.dumps({"event": {"promptEnd": {"promptName": prompt_name}}}))
    await send_event(json.dumps({"event": {"sessionEnd": {}}}))
    await stream.input_stream.close()
    
    # Results
    print(f"\nText outputs: {len(text_output)}")
    print(f"Audio chunks: {len(audio_chunks)}")
    
    if audio_chunks:
        total_audio = b''.join(audio_chunks)
        output_path = '/Users/ChadDHendren/AmazonConnect1/voice_output/nova_raw_test.wav'
        with wave.open(output_path, 'wb') as wav_file:
            wav_file.setnchannels(1)
            wav_file.setsampwidth(2)
            wav_file.setframerate(24000)
            wav_file.writeframes(total_audio)
        print(f"Saved {len(total_audio)} bytes to: {output_path}")


if __name__ == "__main__":
    # Run both tests
    asyncio.run(test_nova_sonic_text_to_speech())
    asyncio.run(test_nova_sonic_raw())
